# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a61e1cb15714be021f5824c830d830a9739b0ad067f17a85bf9029a91db2b513c8a233e371ea777f5ac78d383e13ba4811bc031e4ce8199f63eee6610dca3bd5

test:
  secret_key_base: eb65eaca8aa93685504eed523fc452cb245af703720a2f1fb05cdfced2bfe3a5d76901337be6e0a7e6d18a6e6bf102df13e02e06cc1d3aac891a13f8e68045eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
